---
- name: CV
  hosts: all
  become: true
  become_user: "jtprogru"

  vars:
    full_name: "Michael Savin"
    ansible_distribution: ["Ubuntu", "Debian", "RHEL", "CentOS"]
    practice: ["DevOps", "IaC", "CI/CD/CD", "DaC"]
    ssh_public_key: https://github.com/jtprogru.keys
    instruments: 
      - configuration_managment: ["Ansible", "SaltStack"]
      - version_control: ["GitHub", "GitLab", "Bitrbucket"]
      - task_manager: ["Jira", "Trello"]
      - monitoring: ["Zabbix", "Prometheus", "Grafana"]
      - documentation: ["Confluence", "GiLab/GitHub Wiki", "Notion"]
      - virtualisation: ["Proxmox", "VMware"]
      - containerisation: ["Docker", "LXC"]
    contacts:
      blog: "https://jtprog.ru"
      full_ru_cv: "https://savinmi.ru/"
      email: "mail@jtprog.ru"
      telegram: "@jtprogru"
      twitter: "@jtprogru"

  roles:
    - "{{ become_user }}.infrastructure_engineer"
    - "{{ become_user }}.linux_administrator"
    - "{{ become_user }}.devops_engineer"

