---
- name: CV
  hosts: all
  become: true
  become_user: "jtprogru"

  vars:
    full_name: "Michael Savin"
    ansible_distribution: ["Ubuntu", "Debian", "RHEL", "CentOS"]
    practice: ["DevOps", "IaC", "CI/CD/CD", "DaC"]
    ssh_public_key: "https://github.com/jtprogru.keys"
    instruments: ["Ansible", "SaltStack", "GitHub", "GitLab", "Bitrbucket", "Jira", "Zabbix", "Prometheus", "Grafana",
                  "Confluence", "GiLab/GitHub Wiki", "Notion", "Proxmox", "VMware", "Docker", "DigitalOcean"]
    contacts:
      keybase: "https://keybase.io/jtprog"
      gpg_key: "172103F339C1FCB4"
      full_ru_cv: "https://savinmi.ru/"
      blog: "https://jtprog.ru/"
      telegram: "@jtprogru"

  roles:
    - "{{ become_user }}.sre"
    - "{{ become_user }}.infrastructure_engineer"
    - "{{ become_user }}.linux_administrator"
    - "{{ become_user }}.devops_engineer"
    - "{{ become_user }}.python_dev"
    - "{{ become_user }}.golang_dev"
