"""Shared bits for the profile asset generators (gen_cover.py, gen_metrics.py).

Holds the GitHub GraphQL client, the palette both SVGs are drawn with, and the
card chrome (gradient, dot grid, glow, rounded frame) so the two assets keep
looking like one pair.
"""

from __future__ import annotations

import datetime as dt
import json
import os
import sys
import urllib.error
import urllib.request
from typing import Any
from xml.sax.saxutils import escape

API = "https://api.github.com/graphql"

FONT_MONO = "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace"
FONT_SANS = "ui-sans-serif, -apple-system, Segoe UI, Helvetica, Arial, sans-serif"

# GitHub dark palette.
TEXT = "#e6edf3"
MUTED = "#8b949e"
DIM = "#6e7681"
ACCENT = "#58a6ff"
GREEN = "#3fb950"
YELLOW = "#e3b341"
LINE = "#30363d"
LINE_SOFT = "#21262d"
CARD = "#161b22"

# Contribution calendar levels, dark theme.
LEVELS = {
    "NONE": "#161b22",
    "FIRST_QUARTILE": "#0e4429",
    "SECOND_QUARTILE": "#006d32",
    "THIRD_QUARTILE": "#26a641",
    "FOURTH_QUARTILE": "#39d353",
}

# ~0.6em is the advance width of the monospace faces we ask for; good enough
# to right-align text and to decide where a string has to be cut.
MONO_RATIO = 0.6

GENERATED_MARK = "Generated by scripts/"

# Inside one <text> a single space survives; on a <tspan> boundary XML
# trimming eats it. So separators between tspans are spaced with dx, and SEP
# is only for plain text runs.
SEP = " · "
SEP_DX = 7


def token_from_env(explicit: str | None = None) -> str:
    token = explicit or os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN")
    if not token:
        sys.exit("no token: pass --token or set GITHUB_TOKEN (locally: GITHUB_TOKEN=$(gh auth token))")
    return token


def api(query: str, variables: dict[str, Any], token: str) -> dict[str, Any]:
    payload = json.dumps({"query": query, "variables": variables}).encode()
    request = urllib.request.Request(
        API,
        data=payload,
        headers={
            "Authorization": f"bearer {token}",
            "Content-Type": "application/json",
            "User-Agent": "jtprogru-profile-generator",
        },
    )
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            body = json.load(response)
    except urllib.error.HTTPError as exc:  # surface GitHub's own message
        sys.exit(f"GitHub API error {exc.code}: {exc.read().decode(errors='replace')[:500]}")
    if "errors" in body:
        sys.exit("GitHub API returned errors: " + json.dumps(body["errors"], ensure_ascii=False))
    return body["data"]


def now_utc() -> dt.datetime:
    return dt.datetime.now(dt.timezone.utc)


def thousands(value: int) -> str:
    """5199 -> "5 199" — the separator both assets use."""
    return f"{value:,}".replace(",", " ")


def mono_width(text: str, font_size: float) -> float:
    return len(text) * font_size * MONO_RATIO


def ellipsize(text: str, budget_px: float, font_size: float) -> str:
    """Cut `text` so it fits into `budget_px` of the monospace face."""
    budget = int(budget_px / (font_size * MONO_RATIO))
    if budget <= 1:
        return "…"
    return text if len(text) <= budget else text[: budget - 1] + "…"


def dot_join(parts: list[str], color: str) -> str:
    """Join already-escaped parts with a dimmed middle dot."""
    out = [parts[0]]
    for part in parts[1:]:
        out.append(f'<tspan dx="{SEP_DX}" fill="{color}">·</tspan>')
        out.append(f'<tspan dx="{SEP_DX}">{part}</tspan>')
    return "".join(out)


def wrap(text: str, width: int, lines: int) -> list[str]:
    """Greedy wrap into at most `lines` lines, ellipsis on overflow."""
    if not text:
        return []
    out: list[str] = []
    current = ""
    for word in text.split():
        candidate = f"{current} {word}".strip()
        if len(candidate) <= width:
            current = candidate
            continue
        if current:
            out.append(current)
        if len(out) == lines:
            break
        current = word if len(word) <= width else word[: width - 1] + "…"
    if current and len(out) < lines:
        out.append(current)
    if len(out) == lines and len(" ".join(out)) < len(text.rstrip()):
        out[-1] = out[-1][: width - 1].rstrip() + "…"
    return out[:lines]


def shell(
    *,
    width: int,
    height: int,
    aria: str,
    generator: str,
    body: str,
    generated_at: str,
    glow: tuple[int, int, int, int] = (900, 60, 420, 280),
) -> str:
    """Wrap `body` in the shared dark card: gradient, dot grid, glow, frame."""
    gx, gy, grx, gry = glow
    return f"""<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}" role="img" aria-label="{escape(aria)}">
  <!-- {GENERATED_MARK}{generator} at {generated_at}. Do not edit by hand. -->
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#0d1117"/>
      <stop offset="55%" stop-color="#111823"/>
      <stop offset="100%" stop-color="#0a1a26"/>
    </linearGradient>
    <linearGradient id="accent" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="{ACCENT}"/>
      <stop offset="100%" stop-color="#0e75b6"/>
    </linearGradient>
    <pattern id="grid" width="32" height="32" patternUnits="userSpaceOnUse">
      <circle cx="1" cy="1" r="1" fill="{MUTED}" fill-opacity="0.12"/>
    </pattern>
    <radialGradient id="glow" cx="0.5" cy="0.5" r="0.5">
      <stop offset="0%" stop-color="{ACCENT}" stop-opacity="0.16"/>
      <stop offset="100%" stop-color="{ACCENT}" stop-opacity="0"/>
    </radialGradient>
    <clipPath id="frame">
      <rect x="0" y="0" width="{width}" height="{height}" rx="16"/>
    </clipPath>
  </defs>

  <g clip-path="url(#frame)">
    <rect width="{width}" height="{height}" fill="url(#bg)"/>
    <rect width="{width}" height="{height}" fill="url(#grid)"/>
    <ellipse cx="{gx}" cy="{gy}" rx="{grx}" ry="{gry}" fill="url(#glow)"/>
    <rect x="0" y="0" width="6" height="{height}" fill="url(#accent)"/>

{body}

    <rect x="0.5" y="0.5" width="{width - 1}" height="{height - 1}" rx="16" fill="none" stroke="{LINE}"/>
  </g>
</svg>
"""


def _without_timestamp(text: str) -> str:
    return "\n".join(line for line in text.splitlines() if GENERATED_MARK not in line)


def emit(path: str, svg: str, check: bool) -> int:
    """Write `svg` to `path` unless only the timestamp would change."""
    old = ""
    if os.path.exists(path):
        with open(path, encoding="utf-8") as handle:
            old = handle.read()
    same = _without_timestamp(old) == _without_timestamp(svg)

    if check:
        print(f"{path} is up to date" if same else f"{path} is stale")
        return 0 if same else 1
    if same:
        print(f"{path} is up to date")
        return 0

    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(svg)
    print(f"wrote {path}")
    return 0
